### PR TITLE
Adding Arabic transcript to community video

### LINKED ISSUE #24: Arabic transcript for community video
### Description
I thought that I would take initiative like everyone and add Arabic transcript.

### PR DESCRIPTION
**Pull request by Rahma-AlWadhahi**
Fixes #24
It would be great to have a second pair of eyes to review this pull request when it is finalized.
## Proposed Changes

  - Adding `.sbv` translated file

## Screenshots
- Not applicable

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
Thanks for opening this PR!

**Comment by eddiejaoude** [comment]
Oh awesome 👍 thank you!

**Comment by eddiejaoude** [comment]
@Rahma-AlWadhahi is this still in draft?

**Comment by Rahma-AlWadhahi** [comment]
> @Rahma-AlWadhahi is this still in draft?

Oh no, I will convert it to "Ready for review"

**Comment by eddiejaoude** [comment]
Thank you @Rahma-AlWadhahi 👍

**Comment by eddiejaoude** [comment]
Published https://www.youtube.com/watch?v=z-FKAC0I_VQ

**Pull request merged**
